[package]
name = "r1"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1.29", features = ["full"] }
dashmap = "5.5"
anyhow = "1.0"
local-ip-address = "0.5.1"
systemstat = "0.2.3"
if_chain = "1.0"
once_cell = "1.19"
system_diskinfo = "0.2.1"