[package]
name = "r1"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
num-bigint = "0.4"
hex = "0.4"
futures = "0.3"
serde_json = "1.0"
bytes = "1.5.0"

ft_homomorphic = {git = "ssh://git@code.non-convex.com/lihaohan/ft_homomorphic.git"}
burn = { version = "0.12", features = ["wgpu","train","vision"] }
