[package]
name = "r1"
version = "0.1.0"
edition = "2021"


[dependencies]
axum = { version = "0.6", features = ["headers","ws","multipart"]}
tokio = { version = "1", features = ["full"] }
tokio-util = {version = "0.7", features = ["io"]}
serde = { version = "1.0", features = ["derive"] }
csv = "1.0"